// Generated by Xata Codegen 0.28.0. Please do not edit.
import { buildClient } from '@xata.io/client'
import type { BaseClientOptions, SchemaInference, XataRecord } from '@xata.io/client'

const tables = [
  {
    name: 'uploads',
    columns: [{ name: 'image', type: 'file', file: { defaultPublicAccess: true } }],
  },
  {
    name: 'profiles',
    columns: [
      { name: 'slug', type: 'string', unique: true },
      { name: 'name', type: 'string' },
      { name: 'image', type: 'string' },
      { name: 'height', type: 'string' },
      { name: 'width', type: 'string' },
      { name: 'imageHash', type: 'text' },
    ],
  },
  {
    name: 'photographs',
    columns: [
      { name: 'image', type: 'string' },
      { name: 'name', type: 'string' },
      { name: 'tagline', type: 'string' },
      { name: 'height', type: 'string' },
      { name: 'width', type: 'string' },
      { name: 'profile-slug', type: 'string' },
      { name: 'slug', type: 'string' },
      { name: 'imageHash', type: 'text' },
    ],
  },
] as const

export type SchemaTables = typeof tables
export type InferredTypes = SchemaInference<SchemaTables>

export type Uploads = InferredTypes['uploads']
export type UploadsRecord = Uploads & XataRecord

export type Profiles = InferredTypes['profiles']
export type ProfilesRecord = Profiles & XataRecord

export type Photographs = InferredTypes['photographs']
export type PhotographsRecord = Photographs & XataRecord

export type DatabaseSchema = {
  uploads: UploadsRecord
  profiles: ProfilesRecord
  photographs: PhotographsRecord
}

const DatabaseClient = buildClient()

const defaultOptions = {
  databaseURL: 'https://Rishi-Raj-Jain-s-workspace-80514q.ap-southeast-2.xata.sh/db/image-gallery-cms-with-xata-astro-cloudflare',
}

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables)
  }
}

let instance: XataClient | undefined = undefined

export const getXataClient = () => {
  if (instance) return instance

  instance = new XataClient()
  return instance
}
